name = "amf-exam"
pages_build_output_dir = "."

# Create the DB with: wrangler d1 create amf-questions
# Then paste the returned database_id below.
[[d1_databases]]
binding = "DB"
database_name = "amf-questions"
database_id = "4a792f11-54e4-47b9-aa04-8c4634b3f28d"
